[package]
name = "hawkeye"
version = "0.1.0"
authors = ["Gabe Durazo <gabe@mbtace.com>"]

[dependencies]
chrono = "0.4"
postgres = { version = "0.15", features = ["with-chrono"] }
reqwest = "0.8.6"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"